aws/retrospectiva-master/retrospectiva-master/config/routes.rb
ActionController::Routing::Routes.draw do |map|

  map.root :controller => 'projects'
  map.login   'login',  :controller => 'sessions', :action => 'new'
  map.logout  'logout', :controller => 'sessions', :action => 'destroy'

  map.resource :session, :new => {:secure => :post}
  map.resource :account do |account|
    account.activate 'activate/:username/:code', :controller => 'accounts', :action => 'activate', :username => nil, :code => nil
    account.forgot_password 'forgot_password', :controller => 'accounts', :action => 'forgot_password'
  end
  
  
  pt_collection_methods = { :search => :any, :users => :post }
  pt_member_methods     = { :modify_summary => :put, :modify_content => :put, :modify_change_content => :put, :toggle_subscription => :post }
  
  map.resources :projects do |project|

    project.filter 'central_project'

    project.resources :changesets, :member => { :diff => :get }    
    project.resources :tickets, :collection => pt_collection_methods, :member => pt_member_methods do |ticket|
      ticket.download 'download/:id/:file_name', :controller => 'tickets', :action => 'download', :file_name => /.+/
      ticket.destroy_change ':id', :controller => 'tickets', :action => 'destroy_change', :conditions => { :method => :delete }, :requirements => { :id => /\d+/ }
    end
    project.resources :ticket_reports, :collection => { :sort => :put }    
    project.resources :milestones    
    project.with_options :controller => 'browse' do |browse|
      browse.browse    'browse/*path'
      browse.revisions 'revisions/*path', :action => 'revisions'
      browse.download  'download/*path', :action => 'download'
      browse.diff      'diff/*path', :action => 'diff'
    end
    project.with_options :controller => 'search' do |search|
      search.search    'search'
    end

  end


  map.with_options :controller => 'rss' do |rss|
    rss.rss 'rss'
  end

  map.with_options :controller => 'markup' do |markup|
    markup.markup_preview 'markup/preview.js', :action => 'preview', :format => 'js'
    markup.markup_reference 'markup/reference', :action => 'reference'
  end

  map.admin 'admin', :controller => 'admin/dashboard'
  map.namespace :admin do |admin|
    admin.resources :projects, :collection => { :repository_validation => :any } do |projects|
      projects.resources :ticket_properties, :collection => { :sort => :put } do |properties|
        properties.resources :values, :controller => 'ticket_property_values', :collection => { :sort => :put }
      end
    end
    admin.resources :repositories, :collection => { :validate => :any }
    admin.resources :users, :collection => { :search => :any }
    admin.resources :groups
    admin.resources :tasks, :collection => { :save => :put }
    admin.setup 'setup.:format', :controller => 'setup', :conditions => { :method => :get }    
    admin.setup 'setup.:format', :controller => 'setup', :action => 'save', :conditions => { :method => :put }    
    admin.extensions 'extensions', :controller => 'extensions'
  end

  Retrospectiva::ExtensionManager::Routes.apply(map)
end

aws/retrospectiva-master/retrospectiva-master/app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :groups, 
    :order => 'groups.name',
    :uniq => true

  has_many :changesets, :dependent => :nullify
  has_many :assigned_tickets, 
    :class_name => 'Ticket', 
    :foreign_key => 'assigned_user_id',
    :dependent => :nullify
  has_many :tickets, :dependent => :nullify
  has_many :ticket_changes, :dependent => :nullify
  has_many :login_tokens, :dependent => :destroy
  

  validates_uniqueness_of :username, :allow_blank => true, :case_sensitive => false
  validates_length_of     :username, :within => 3..40
  validates_format_of     :username, :with => /^[^\s]+$/

  validates_presence_of   :name, :email, :unless => :public?
  validates_uniqueness_of :email, :allow_blank => true, :case_sensitive => false, :unless => :public?
  validates_as_email :email, :allow_blank => true

  validates_confirmation_of :plain_password

  validates_presence_of :plain_password, :on => :create
  validates_length_of :plain_password, :within => 6..40, :on => :create, :allow_blank => true

  validates_uniqueness_of :scm_name, :case_sensitive => false, :allow_blank => true
  validates_inclusion_of :time_zone, :in => ActiveSupport::TimeZone::MAPPING.keys

  attr_accessible :name, :plain_password, :plain_password_confirmation, :time_zone
  attr_accessor_with_default :plain_password, ''
  attr_accessor_with_default :plain_password_confirmation, ''
  
  named_scope :active, :conditions => ['active = ?', true]
  
  class << self

    def current=(user)
      @current_user = user
    end
    
    def current
      @current_user.is_a?(User) ? @current_user : public_user
    end
    
    def public_user
      User.find_by_username 'Public', :include => {:groups => :projects}
    end

    def searchable_column_names
      ['username', 'name', 'email', 'scm_name'].map do |name|
        "#{quoted_table_name}.#{name}"
      end
    end
    
    def authenticate(params)
      user = params.is_a?(Hash) ? identify(params[:username]) : nil
      if user
        success = if secure_auth? 
          user.valid_password_hash?(params[:hash], params[:tan])
        else
          user.valid_password?(params[:password])
        end
        return user if success
      end     
      nil
    end  

    # Returns an active user for given username or email address
    def identify(username_or_email)
      return nil if username_or_email.blank? or username_or_email == 'Public'
      
      if username_or_email =~ /@/ 
        active.find_by_email(username_or_email)
      else
        active.find_by_username(username_or_email)
      end      
    end

    def per_page
      10
    end
    
    protected
      
      def secure_auth?
        RetroCM[:general][:user_management][:secure_auth]
      end

  end

  # Returns true is user is the currently logged-in user, else false
  def current?
    self == User.current
  end
 
  # Returns true is user is the public user, else false
  def public?
    ( new_record? ? username : username_was ) == 'Public'
  end

  # Returns true is user is the last available administrator
  def last_admin?
    admin_was && self.class.count(:all, :conditions => { :admin => true }) == 1
  end
  
  # Returns true if given plain password matches, else false
  def valid_password?(plain)
    password == hash_crypt(plain.to_s)    
  end
  
  # Returns true if given hash digest matches the plain password for a given tan
  def valid_password_hash?(hash, token = nil)    
    Digest::SHA1.hexdigest("#{SecureToken.spend(token)}:#{password}") == hash    
  end

  # Returns all projects available for the user
  def projects
    @projects ||= AssociationProxies::UserProjects.instantiate(self)
  end

  # Resets the password attribute, expects plain password
  def reset_password(plain)
    self.password = hash_crypt(plain)
  end

  # Returns the salt attribute, resets it automatically if blank
  def salt
    read_attribute(:salt) || reset_salt
  end
  
  # Returns the activation_code attribute, resets it automatically if blank
  def activation_code
    read_attribute(:activation_code) || reset_activation_code
  end

  # Returns the private_key attribute, resets it automatically if blank
  def private_key
    read_attribute(:private_key) || reset_private_key
  end

  # Resets user's salt
  def reset_salt
    self.salt = Randomizer.string
  end

  # Resets user's activation code
  def reset_activation_code
    self.activation_code = Randomizer.pronounceable
  end
  
  # Resets user's private key
  def reset_private_key
    self.private_key = ActiveSupport::SecureRandom.hex(32)
  end
  
  def has_access?(path_or_hash, method = :get)
    path_or_hash = path_or_hash.dup
    path = path_or_hash.is_a?(Hash) ? ActionController::Routing::Routes.generate(path_or_hash) : path_or_hash
    path.sub!(%r/^#{Regexp.escape(ActionController::Base.relative_url_root.to_s)}/, '')  # Remove URL prefix
    path.sub!(/\?.+?$/, '') # Remove query string
    options = ActionController::Routing::Routes.recognize_path(path, :method => method)

    controller = "#{options[:controller].camelize}Controller".constantize
    action = options[:action] ? options[:action].to_s : 'index'
    project = options[:project_id] ? Project.find_by_short_name(options[:project_id]) : Project.current
    controller.authorize?(action, options, self, project)
  end 
  
  def permitted?(resource, action, *args)
    return false unless active?
    return true if admin?
    
    options    = args.extract_options!
    project    = options[:project] || Project.current
    permission = RetroAM.permission_map.find(resource, action)
    
    if project && permission
      has_permission = project_permission?(project, resource, action)
      permission.custom? ? permission.evaluate(project, self, has_permission, *args) : has_permission
    else
      false
    end
  end

  def serialize_only
    [:id, :username, :name]
  end

  protected

    class PermissionSet < Hash

      def union(permissions)        
        permissions.each do |ressource, names|
          self[ressource] ||= []
          self[ressource] = (self[ressource] + names).reject(&:blank?).uniq.sort
        end
        self
      end

    end

    def project_permissions(project)
      return {} unless project

      @cached_permissions ||= {}
      @cached_permissions[project.id] ||= groups.inject(PermissionSet.new) do |result, group|
        result.union(group.permissions) if group.has_access_to_project?(project)
        result
      end
    end

    def project_permission?(project, resource, action)
      project_permissions(project)[resource.to_s].include?(action.to_s) rescue false
    end

    def rollback_changes!
      changed_attributes.each { |attr, value_was| self[attr] = value_was }      
    end

    def validate
      if public? && admin?
        errors.add :admin, :not_for_public
      end
      if !admin? && last_admin?
        errors.add :admin, :last_available
      end
      if current? && admin_was && !admin?
        errors.add :admin, :invalid_downgrade
      end
      if public? && !active?
        errors.add :active, :must_be_active
      end
      if current? && active_was && !active?
        errors.add :active, :own_account_must_be_active
      end
      if public? && changed? && !new_record?
        errors.add_to_base _('Public user cannot be modified.')
        rollback_changes!
      end
      errors.empty?
    end

    # Make sure user is:
    # * NOT the Public use
    # * NOT the last admin
    # * NOT the currently logged-in user
    def before_destroy
      if public?
        errors.add_to_base _('Public user cannot be deleted.')
      end
      if last_admin?
        errors.add_to_base _("Cannot delete. User '%{username}' is the last available admin.", :username => username)
      end
      if current?
        errors.add_to_base _('You cannot delete your own account.')
      end
      errors.empty?
    end

    def hash_crypt(plain)
      Digest::SHA1.hexdigest("+++{{#{plain}:#{salt}}}---")
    end
end

aws/retrospectiva-master/retrospectiva-master/app/controllers/admin/users_controller.rb
#--
# Copyright (C) 2009 Dimitrij Denissenko
# Please read LICENSE document for more information.
#++
class Admin::UsersController < AdminAreaController
  before_filter :paginate_users, :only => [:index, :search]
  before_filter :find_user, :only => [:show, :edit, :update, :destroy]
  before_filter :find_groups, :only => [:new, :edit]

  def index
    respond_to do |format|
      format.html
      format.xml  { render :xml => @users }
    end
  end

  def search
    respond_to(:js)
  end

  def new
    @user = User.new(params[:user])

    respond_to do |format|
      format.html
      format.xml  { render :xml => @user }
    end
  end

  def create
    @user = User.new(params[:user])

    respond_to do |format|
      @user.send(:attributes=, params[:user], false)
      if @user.save
        flash[:notice] = _('User was successfully created.')
        format.html { redirect_to admin_users_path }
        format.xml  { render :xml => @user, :status => :created, :location => admin_user_path(@user) }                
      else
        find_groups
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }        
      end    
    end    
  end

  def show
    respond_to :xml
  end

  def edit
  end

  def update
    active_was = @user.active?
    @user.send(:attributes=, params[:user], false)
    
    respond_to do |format|
      if @user.save
        successful_update(active_was)
        format.html { redirect_to admin_users_path }
        format.xml { head :ok }
      else
        find_groups
        format.html { render :action => 'edit' }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }                
      end
    end
  end

  def destroy
    @user.destroy
    
    respond_to do |format|
      if @user.errors.empty?
        flash[:notice] = _('User was successfully deleted.')
        format.html { redirect_to admin_users_path }
        format.xml { head :ok }
      else
        flash[:error] = [_('User could not be deleted. Following error(s) occurred') + ':'] + @user.errors.full_messages
        format.html { redirect_to admin_users_path }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }                
      end
    end
  end

  protected
    
    def find_user
      @user = User.find(params[:id])       
    end

    def paginate_users
      conditions = PlusFilter::Conditions.new do |c|
        c << Retro::Search::exclusive(params[:term], *User.searchable_column_names)
      end
      @users = User.paginate(
        :conditions => conditions.to_a,
        :order => "CASE users.id WHEN #{User.public_user.id} THEN 0 ELSE 1 END, users.admin DESC, users.name",
        :include => [:groups],
        :per_page => params[:per_page],
        :page => params[:page]
      )
    end
    
    def find_groups
      @groups = Group.find :all,
        :conditions => ['id <> ?', Group.default_group.id],
        :order => 'name'
    end
  
    def successful_update(active_was)
      flash[:notice] = [_('User was successfully updated.')]
      if @user.active? && !active_was
        flash[:notice] << _('User account was activated.')
        if admin_user_activation? && params[:send_notification]
          flash[:notice].first << (' ' + _('A notification was sent to the user.'))
          Notifications.queue_account_activation_note(@user)
        end
      end      
    end

  private

    def admin_user_activation?
      RetroCM[:general][:user_management][:activation] == 'admin'      
    end
  
end

aws/retrospectiva-master/retrospectiva-master/app/views/admin/users/_core.html.erb
<% f.fieldset do -%>
  <%= f.label :username, _('Username') + ':', :required => true -%>
  <%= f.text_field :username, :disabled => disabled -%>
<% end -%>

<% f.fieldset do -%>
  <%= f.label :email, _('Email') + ':', :required => true -%>
  <%= f.text_field :email, :disabled => disabled -%>
<% end -%>

<% f.fieldset do -%>
  <%= f.label :name, _('Full name') + ':', :required => true -%>
  <%= f.text_field :name -%>
<% end -%>

<% f.fieldset do -%>
  <%= f.label :plain_password, _('Password') + ': ' + 
        ( f.object.new_record? ? '' : info_image(:title => _('Leave password field blank, unless you actually want to change your password.')) ),
      :required => f.object.new_record? -%>
  <%= f.password_field :plain_password, :explain => _('Password') %>
  <%= f.password_field :plain_password_confirmation, :explain => _('Confirmation') -%>
<% end -%>

<% f.fieldset do -%>
  <%= f.label :time_zone, _('Time zone') + ':' -%>
  <%= f.time_zone_select :time_zone %>
<% end -%>

aws/retrospectiva-master/retrospectiva-master/app/views/admin/users/_form.html.erb
<%= f.error_messages %>
<%= render :partial => 'admin/users/core', :locals => {:f => f, :disabled => false} %>
<%= view_extensions :user, :fields, :admin, :locals => { :f => f } %>

<% f.fieldset do -%>
  <%= f.label :scm_name, _('SCM name') + ':' -%>
  <%= f.text_field :scm_name -%>
<% end -%>

<% f.fieldset do -%>
  <%= f.label_tag _('Options') + ':' -%>
  <%= f.check_box :admin %>
  <%= f.label :admin, _('Administrator'), :class => 'choice' %>  
  <% if controller.action_name == 'edit' || RetroCM[:general][:user_management][:activation] == 'auto' -%>
    <br/>
    <%= f.check_box :active %>
    <%= f.label :active, _('Active'), :class => 'choice' %>
  <% end -%>
  <%= view_extensions :user, :options, :admin, :locals => { :f => f } %>
<% end -%>

<%= render :partial => 'groups', :locals => { :f => f } %>

aws/retrospectiva-master/retrospectiva-master/app/views/admin/users/_groups.html.erb
<% f.fieldset do -%>
  <%= f.label_tag _('Groups') + ':' -%>
  <%= hidden_field_tag "#{f.object_name}[group_ids][]", Group.default_group.id, :id => "user_group_ids_#{Group.default_group.id}" -%>
  <%= f.check_boxes :group_ids, @groups.map {|i| [h(i.name), i.id] } %>

  <div class="break quieter"><%= _('ATTENTION: Group settings will be ignored if the \'Administrator\' option is selected!') %></div>
<% end -%>

aws/retrospectiva-master/retrospectiva-master/app/views/admin/users/_header.html.erb
<%= render :partial => '/admin/shared/header' %>
<%= breadcrumbs link_to(_('Users'), admin_users_path), h(@page_title) %>

aws/retrospectiva-master/retrospectiva-master/app/views/admin/users/_user.html.erb
<tr class="<%= cycle('odd', 'even') -%> record">
  <td class="centered"><%= user_gravatar(user) %></td>
  <td>
    <span class="strong"><%=h user.name %> (<%=h user.username %>)</span><br/>
    <%= mail_to user.email, nil, :encode => :hex %>
  </td>  
  <td class="centered"><%= boolean_format user.active?, _('Active'), _('Inactive') %></td>
  <td class="small" title="<%=h ActiveSupport::TimeZone[user.time_zone].to_s %>"><%= truncate h(ActiveSupport::TimeZone[user.time_zone].to_s) %></td>
  <td class="small">
    <% if user.admin? -%>
      <%= content_tag('em', _('Administrator')) %>        
    <% else -%>        
      <%=h user.groups.map(&:name).join(', ') %>
    <% end -%>    
  </td>
  <td class="actions righted span-4">
    <%= link_to _('Edit'), edit_admin_user_path(user) %>

    <% if user.current? || user.public? || user.last_admin? -%>
      <span class="inactive"><%= _('Delete') %></span>
    <% else -%>
      <%= link_to _('Delete'), admin_user_path(user), options_for_destroy_link -%>
    <% end -%>
  </td>
</tr>

aws/retrospectiva-master/retrospectiva-master/app/views/admin/users/edit.html.erb
<% @page_title = _('Edit user') -%>
<%= render :partial => 'header' %>

<% plus_form_for(@user, :url => admin_user_path(@user)) do |f| -%>
  
  <% if @user.public? -%>
    <%= f.info @page_title %>
    <%= f.error_messages %>

    <% f.fieldset do -%>
      <%= f.label :username, _('Username') + ':', :required => true -%>
      <%= f.text_field :username, :disabled => true -%>
    <% end -%>
    
    <%= render :partial => 'groups', :locals => { :f => f } %>
    
  <% else -%>
    <%= render :partial => '/admin/shared/form_header', :locals => {:f => f} %>
  
    <% f.fieldset do -%>
      <%= f.label_tag _('Email notification') %>
      <div>
        <%= check_box_tag 'send_notification', 1, true %>
        <%= f.label_tag _('Notify user on account activation'), :for => 'send_notification', :class => 'choice' %>
      </div>
      <div class="break quiet">
        <%= _('This setting only applies if you enable the \'Activate\' checkbox') -%>
      </div>
    <% end if RetroCM[:general][:user_management][:activation] == 'admin' && !@user.active? -%>
  <% end -%>

  <%= render :partial => '/admin/shared/form_footer', :locals => { 
        :f => f, :label => _('Update'), :collection_path => admin_users_path } %>

<% end -%>
<%= top_link %>

aws/retrospectiva-master/retrospectiva-master/app/views/admin/users/index.html.erb
<% @page_title = _('Users') -%>
<%= render :partial => '/admin/shared/index_header' %>

<table class="record-list">
  <thead>
    <% top_navigation_for(@users, _('Create a new user'), new_admin_user_path, 4, 2) do -%>
      &mdash; <%= _('Search') %>: <%= search_field_tag %>
    <% end -%>
    <tr>
      <th colspan="2"><%= _('User') %></th>
      <th class="centered"><%= _('Active') %></th>
      <th><%= _('Time zone') %></th>
      <th><%= _('Groups') %></th>
      <th>&nbsp;</th>
    </tr>
  </thead>

  <%= bottom_navigation_for(@users, 4, 2) %>

  <tbody id="users">
    <%= render :partial => 'user', :collection => @users %>
  </tbody>
</table>

<%= observe_field 'term',
      :frequency => 1,
      :url => search_admin_users_path(:format => :js),
      :with => "'term=' + encodeURIComponent(value)" -%>

aws/retrospectiva-master/retrospectiva-master/app/views/admin/users/new.html.erb
<% @page_title = _('Create a new user') -%>
<%= render :partial => 'header' %>

<%= render :partial => '/admin/shared/new_form', :locals => {
      :record => @user,
      :collection_path => admin_users_path } %>